### ISSUE TITLE
Shooter not work!

### ISSUE THREAD

**Issue by 1chooo** [IzYoBoiJay/ASCII-Space-Shooter#1]
# Shooter Not Work!

I truly appreciate the project you have created, which has also been a great source of inspiration for me. However, I encountered a "SHOOTER NOT WORK" when attempting to clone your project onto my localhost. I recorded the situation I have met and I would pasted it below. If further assistance is needed to resolve this issue, please feel free to DM me. Thank you very much!

## Shooter Not Work Situation

https://user-images.githubusercontent.com/94162591/232936768-60052bcb-8e64-4a3d-b974-0de67a9b277f.mov

Thanks a lot!

**Comment by IzYoBoiJay** [comment]
Hi @1chooo! See the latest commit, I believe this fixes the issue you experienced. I created this project 2 years ago when I first learned to program in general and in C++. It was nostalgic and fun to finally see the solution after much experience.

The ncurses C++ library getch() and wgetch() calls are "blocking" calls, and will wait indefinitely for input. You shall see the fix I have implemented removes this delay by changing the wgetch() call in the code into a "non-blocking" call, and instead places a 100ms delay through wtimeout() to wait for the input. Otherwise, it continues as normal.

While this is a fix, it's still far from perfect in terms of performance and efficiency. I would love to hear your or anyone's thoughts. I chose this solution for its straightforwardness and simplicity given the utilization of the library provided. Nonetheless, I have a few of my own:

1) If you are familiar with operating systems and multithreading, it is a good idea to use pthreads() to control the game and its AI.

2) One can use a finite-state machine of movement for the player such as enumerations like {IDLE, MOVE_UP, MOVE_DOWN, etc.} that will continuously process. This can also be wonderful for learning animations in game development in my experience.

[https://github.com/IzYoBoiJay/ASCII-Space-Shooter/commit/6d56244bd117f898d771efd5d66ea13736df78a9](url)

If it's a different issue you are looking at, please feel free to let me know!

Cheers,
IzYoBoiJay

**Comment by 1chooo** [comment]
Hi, @IzYoBoiJay! Thank you for your responses and support. I am currently working on my own C++ projects to enhance my OOP skills and better understand the linker between cpp files. To achieve my objectives, I have decided to use the `ncurses.h` library. If you have any additional suggestions, please do not hesitate to share them. I am always eager to learn.

Best,
1chooo
